FROM golang:latest

EXPOSE 8011

RUN mkdir -p /home/go/app

WORKDIR /home/go/app
ENV BRANCH = "master"

COPY . .
RUN go env -w GOPROXY="https://goproxy.cn" && \
    go get 

CMD ["sh", "-c", "git fetch && git checkout $BRANCH -f && git pull --ff-only && go get && bash"]