FROM golang:latest

EXPOSE 8011

RUN mkdir -p /home/go/app

WORKDIR /home/go/app
ENV BRANCH = "master"

COPY . .
RUN go env -w GOPROXY="https://goproxy.cn"
RUN go get 

CMD ["sh", "-c", "git fetch && git checkout $BRANCH && git pull --ff-only && go get && bash"]