version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD:?err}
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - ${PORT:-27017}:27017
